In [1]:
print("Hello World")

Hello World


In [2]:
x = 2
if x >= 5:
    print("Hi guys")
else:
    print("Bye Guys")


Bye Guys


In [3]:
import math

In [4]:
math.sqrt(36)

6.0

In [5]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.9/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in 

In [6]:
import numpy as np

In [7]:
np.__version__

'2.0.2'

In [8]:
import sys; import numpy as np
print("Python Path:", sys.executable)
print("NumPy Path:", np.__file__)


Python Path: /Users/sontudaniel/PyCharmMiscProject/.venv/bin/python
NumPy Path: /Users/sontudaniel/PyCharmMiscProject/.venv/lib/python3.9/site-packages/numpy/__init__.py


In [9]:
import pandas as pd

In [10]:
pd.__version__

'2.3.3'

In [11]:
list_1 = [1,2,3]
list_1
list_2 = [3,4,5]

In [12]:
list_1.extend(list_2)
list_1

[1, 2, 3, 3, 4, 5]

In [13]:
list_2


[3, 4, 5]

In [14]:
print ("Hello Github Green Dots")

Hello Github Green Dots


In [15]:
import numpy as np

In [16]:
s = 5

In [17]:
s

5

In [18]:
v = np.array([5,-2,4])

In [19]:
v

array([ 5, -2,  4])

In [20]:
m = np.array([[5,12,6],[-3,0,14]])

In [21]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [22]:
type(s)

int

In [23]:
type(v)

numpy.ndarray

In [24]:
s_array = np.array(5)

In [25]:
s_array

array(5)

In [26]:
type(s_array)

numpy.ndarray

In [27]:
m.shape

(2, 3)

In [28]:
v.shape

(3,)

In [29]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [30]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [31]:
#Creating a tensor
m1=np.array([[5.2,12,6],[-3.8,0,14]])
m1

array([[ 5.2, 12. ,  6. ],
       [-3.8,  0. , 14. ]])

In [32]:

m2=np.array([[9.5,8,7],[1.3,3,-5]])
m2

array([[ 9.5,  8. ,  7. ],
       [ 1.3,  3. , -5. ]])

In [33]:
t = np.array([m1,m2])

In [34]:
t

array([[[ 5.2, 12. ,  6. ],
        [-3.8,  0. , 14. ]],

       [[ 9.5,  8. ,  7. ],
        [ 1.3,  3. , -5. ]]])

In [35]:
t.shape

(2, 2, 3)

In [36]:
m1+m2

array([[14.7, 20. , 13. ],
       [-2.5,  3. ,  9. ]])

In [37]:
m1-m2

array([[-4.3,  4. , -1. ],
       [-5.1, -3. , 19. ]])

In [38]:
v1 = np.array([1,2,3,4,5,6])
v2 = np.array([6,5,4,3,2,1])

In [39]:
type(232)

int

Addition of vectors of different lenghts

In [40]:
v3 = np.array([1,2,3,4,5,6])
v3

array([1, 2, 3, 4, 5, 6])

In [41]:
v4 = np.array([1,2,3,4,5,7])
v4

array([1, 2, 3, 4, 5, 7])

In [42]:
v3+v4

array([ 2,  4,  6,  8, 10, 13])

Exceptions (additions of scalar+vectors)

In [43]:
1+v3

array([2, 3, 4, 5, 6, 7])

In such case, every element from the vector, was added +1

In [44]:
r4=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
r4

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [45]:
10+r4

array([[11, 12, 13, 14, 15, 16],
       [11, 12, 13, 14, 15, 16]])

Also exception was made here. Each element was added +10

Transposing Matrices

In [46]:
A = np.array([[5,12,5],[3,0,-14]])
A

array([[  5,  12,   5],
       [  3,   0, -14]])

In [47]:
A.T

array([[  5,   3],
       [ 12,   0],
       [  5, -14]])

dDot Product

D

DOT PRODUCT

In [55]:
x=np.array([2,8,-4])
x

array([ 2,  8, -4])

In [54]:
y=np.array([1,-7,3])
y

array([ 1, -7,  3])

In [59]:
x*y

array([  2, -56, -12])

In [71]:
#wanted to get a clean response
print(np.dot(x,y))

-66


In [72]:
u=np.array([0,2,5,8])
v=np.array([20,3,4,-1])


In [73]:
print(np.dot(u,v))

18
